### ISSUE TITLE
Guides > Create and manage booking pages

### ISSUE THREAD

**Issue by saintmac** [saintmac/vyte-api-v2-doc#26]
Intro:

- [x] "You should now be able to access the API with your API key, if you aren't, read our Getting started guide" (avec un lien)
"Let's see how you can use Vyte API to automate your scheduling workflow."

- [ ] in the payload example, I think it should be `emails: ["john.doe@example.com"]` instead of `email: "john.doe@example.com"` but maybe I'm wrong

- [x] "Vyte.in dashboard": -> "Vyte dashboard" (we don't use the Vyte.in brand anymore, Vyte only)

- [x] "Vyte.in dashboard" -> /!\ the link points to www-dev2. Probably do a project search to make sure no url points to dev2 anymore and all to production

- [x] Vyte page will look like this: no screenshot!

- [x] PUT Users. Now that we have a Vyteme endpoint wouldn't it be clearer to use it?

# Create and set up the Vyte Page

- [x] "teh Vyte Page" -> "the Vyte Page"

 - [x] `"nickname": "jonh-doe-acme"` -> `"nickname": "john-doe-acme"` (and replace the url in the "Access the Vyte Page" section

 - [x] in the payload add `custom.slot_view: true` (and update screenshot)

- [x] it would be nice to set as user picture_url that actually works so that the vyte page doesn't show forever loading dots

**Comment by ladislas14** [comment]
> Intro:
> 
> * [x]  "You should now be able to access the API with your API key, if you aren't, read our Getting started guide" (avec un lien)
>   "Let's see how you can use Vyte API to automate your scheduling workflow."

* [ ]  in the payload example, I think it should be `emails: ["john.doe@example.com"]` instead of `email: "john.doe@example.com"` but maybe I'm wrong
**--> this is how the User API works** 

> * [x]  "Vyte.in dashboard": -> "Vyte dashboard" (we don't use the Vyte.in brand anymore, Vyte only)
> * [x]  "Vyte.in dashboard" -> /!\ the link points to www-dev2. Probably do a project search to make sure no url points to dev2 anymore and all to production
> * [x]  Vyte page will look like this: no screenshot!
> * [x]  PUT Users. Now that we have a Vyteme endpoint wouldn't it be clearer to use it?
> 
> # Create and set up the Vyte Page
> * [x]  "teh Vyte Page" -> "the Vyte Page"
> * [x]  `"nickname": "jonh-doe-acme"` -> `"nickname": "john-doe-acme"` (and replace the url in the "Access the Vyte Page" section
> * [x]  in the payload add `custom.slot_view: true` (and update screenshot)
> * [x]  it would be nice to set as user picture_url that actually works so that the vyte page doesn't show forever loading dots
