### ISSUE TITLE
Guides > Add scheduling features to your app or platform

### ISSUE THREAD

**Issue by saintmac** [saintmac/vyte-api-v2-doc#33]
- [x] After "... to your app or platform.", add "This will let you easily add a button in your product to schedule a meting with 1 person or a group".

- [x] "as path parameters" -> "as query parameters"

- [x] "a event creation" -> "an event creation"

- [x] "idea of third-party and" -> "idea of third-party app and"

- [x] "will able us" -> "will enable us"

- [x] "register a new third-party" -> "register as a new third-party app"

- [x] `/v2/third_parties/new` -> document query parameters

- [x] `/v2/third_parties/new` -> make clear that this request needs to be authenticated with an api_key

- [x] explain that the `app_id` is the `_id` field in the response. Explain that the `app_scret` field is the `secret` field in the response. And explain that they should take note of their `app_id` and `app_secret` as they will be very useful in the future.

- [x] agid: explain that you can actually pass several of those, by comma separating them

- [x] `cm`: "optional if the user already has a Vyte account and is expected to be logged in with it on the same browser"

- [x] `cn`. : useful if the creator doesn't have a Vyte account yet.

- [x] `ct`: "Used to authenticate the request". "optional if the user already has a Vyte account and is expected to be logged in with it on the same browser". See below how to generate such a token.

- [x] `em` -> `im` (watch out there is indeed an `em` parameter but for invitee names it is `in`)

- [x] "let's try our new link:": add that "it is expected that the final creation of the meeting will fail as these credentials are fake"

**Comment by TatianaLekhatkova** [comment]
I suppose, that "em -> iM" should be "em -> iN", the mistake was about invitees Names, not Mails.
