### ISSUE TITLE
Guides > Set up team booking

### ISSUE THREAD

**Issue by saintmac** [saintmac/vyte-api-v2-doc#34]
- [x] "group your user" -> "group your users"

- [x] "we will see how to create a team's event." -> "we will see how to book a team event"

- [x] "a team's event isn't an event between the member of a team. A team event allow you to create new appointment with someone of the team." -> "a team event isn't an event between the members of a team. A team event allows you to book an appointment with a member of the team."

- [x] "team's event" -> "team event"

- [x] "But to begin, " -> ""

- [x] "level_name": "company" -> "level_name": "department"

- [x] "As we explained before, the Team API allow" -> "The Team API allows"

 - [x] "We get in response the create event and we can see that the creator was automatically chose " -> "We get in response the event created and we can see that the creator was automatically chosen"

**Comment by TatianaLekhatkova** [comment]
Done.
