### ISSUE TITLE
Guides -> "Use our web components"

### ISSUE THREAD

**Issue by saintmac** [saintmac/vyte-api-v2-doc#35]
- [x] emails: add: "You can pass a list of emails by comma separating them. Slots returned will be slots when all of those users are available"

 - [x] users: add: "You can pass a list of user_ids by comma separating them. Slots returned will be slots when all of those users are available"

 - [x] ndays: "Number of days you want the view to show"

- [x] lang: "Language of the even" -> "Language and locale of the component"

 - [x] one-column: "(vs 1 column per day which)" -> "(vs 1 column per day)

- [x] start-at-first-availability: "to your first availability." -> "to the first day that has an available slot."

 - [x] nslots: defaults to 10. "Number of slots max shown per day." -> "Number of slots max shown per day by default. The user can then click on a "view more slots" button to see all the slots available"

 - [x] "The following code show you how to integrate it easily:" -> "The following code shows you how to integrate our web component easily"

 - [x] `<!-- Mandatory scripts -->` -> `

**Comment by TatianaLekhatkova** [comment]
Corrections added.
